### ISSUE TITLE
Support streaming URL

### ISSUE THREAD

**Issue by linus-dev** [paolotremadio/homebridge-automation-chromecast-play#1]
Hi,

I put my streaming URL from MotionEye in the media.json file but got: 
`/usr/local/lib/node_modules/homebridge-automation-chromecast-play/chromecast-play.js:13
      throw new Error('Mime type not supported');
`

Are streaming URL's not supported or have I configured the config wrong?

Also, when im trying with a mp3 file I get:
`/usr/local/lib/node_modules/homebridge-automation-chromecast-play/node_modules/mdns/lib/resolver_sequence_tasks.js:199
  var e = new Error(syscall + ' ' + errorno);
          ^`
This is my media.json

>  {
    "name": "Overvakningskamera1",
    "url": "https://---------.se/test1.mp3",
    "author": {
      "name": "Overvakningskamera"
    }
  }
]

**Comment by paolotremadio** [comment]
Hi,

What streaming protocol are you using? Also, what OS / distro (including version) are you running homebridge on?

**Comment by linus-dev** [comment]
@paolotremadio 
Thank you for the answer.

Streaming protocol is MJPEG I think.
Running Raspbian Stretch Lite Version 9

**Comment by paolotremadio** [comment]
Ok, I can see a couple of issues.

The first one is with the mime type library I'm using. It is quite simple, it tries to detect the mime type from the URL (using the file extension). Now, I could fix that by adding a field in the JSON to set the mime type. Problem is, chromecast does not support MJPEG (see https://developers.google.com/cast/docs/media).

Second issue is the plugin itself. This is the first version, it supports only "buffered" content, no live stream. Once again, it can be fixed.

About the MP3 error, can you send me the JSON you are using to configure this accessory in homebrige? I suspect the chromecast name is wrong or something like that :)

**Comment by linus-dev** [comment]
Hi,

The URL in my media.json goes to a page that can output multiple livestreams (motioneye). Is it possible to have a similar function like the one on Chrome when you stream the whole tab? 

This is my conf.json for homebridge, "chromecastDeviceName" is taken from my Google Home app. 
`
    {
      "accessory": "AutomationChromecastPlay",
      "name": "Living Room Play",
      "chromecastDeviceName": "Kök",
      "mediaFile": "/home/pi/media.json"
    }`

Thank you for helping me!

**Comment by paolotremadio** [comment]
I have a “good” news for you: I’m able to reproduce the issue, it is related to raspberry pi (as this plugin works perfectly on Mac and Linux). I’m gonna dig deeper and find the solution.

I don’t think it is possible. The “Cast” APIs are poorly documented. What this plugin is doing is wrapping the castv2-client library and expose it to homebridge. Let’s see if we can work around this: can you access this page you’re talking about, using the chromium on the GUI of your raspberry pi?

Also, You’re welcome :)

**Comment by linus-dev** [comment]
Running Stretch Lite, only have access to the command line.

**Comment by paolotremadio** [comment]
Hi @anglaborg, sorry for the late reply.

I've just released a new version that supports both live streams and specifying the MIME type in the config file. I've also fixed the bug with Raspberry PI that was stopping the plugin from working.

About your scenario, can you investigate a bit further about how are the multi-camera displayed together on the same screen? Are they just displayed side-by-side in the HTML of the page you open using your browser?

**Comment by linus-dev** [comment]
When I press the switch in homebridge, this is what happens: https://pastebin.com/jYjCahY
Have reinstalled the plugin

**Comment by paolotremadio** [comment]
The pastebin link seems broken. Can you send it again?
