### ISSUE TITLE
TypeError: Cannot read property 'launch' of null

### ISSUE THREAD

**Issue by aaldhaher** [paolotremadio/homebridge-automation-chromecast-play#10]
I’m seeing a weird problem where starting Audio casting takes down all of Homebridge. Here is the traceback:

Jan 08 16:12:16 raspberrypi homebridge[24529]: [08/01/2023, 16:12:16] TypeError: Cannot read property 'launch' of null
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at PlatformSender.launch (/usr/lib/node_modules/homebridge-automation-chromecast-play/node_modules/castv2-client/li
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at ChromecastPlay.launchPlayer (/usr/lib/node_modules/homebridge-automation-chromecast-play/chromecast-play.js:79:2
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at /usr/lib/node_modules/homebridge-automation-chromecast-play/chromecast-play.js:65:12
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at Client.<anonymous> (/usr/lib/node_modules/homebridge-automation-chromecast-play/node_modules/castv2-client/lib/s
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at Object.onceWrapper (events.js:421:28)
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at Client.emit (events.js:315:20)
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at TLSSocket.<anonymous> (/usr/lib/node_modules/homebridge-automation-chromecast-play/node_modules/castv2/lib/clien
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at Object.onceWrapper (events.js:421:28)
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at TLSSocket.emit (events.js:315:20)
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1522:10)
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at TLSSocket.emit (events.js:315:20)
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at TLSSocket._finishInit (_tls_wrap.js:932:8)
Jan 08 16:12:16 raspberrypi homebridge[24529]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

I’m running version 0.0.7 of the plugin. I have not updated anything in my set up in a long time, not sure what has broken here. Any ideas?

**Comment by paolotremadio** [comment]
Hi, I’m sorry but this plug-in is not maintained anymore so feel free to raise a PR to fix the issue. It is likely something to do with one of the dependencies.
